name: oodx-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - glpk=4.65
  - ipopt=3.14.4
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - json5=0.9.6
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - notebook=6.4.11
  - numpy=1.22.3
  - numpy-base=1.22.3
  - pyomo=6.2
  - pytorch=1.10.2
  - scikit-learn=1.0.2
  - scikit-optimize=0.9.0
  - scipy=1.8.0
